source 'https://github.com/CocoaPods/Specs.git'

target 'MCKillSwitchExample', :exclusive => true do
  pod "MCKillSwitch", :path => "../"
end

target 'MCKillSwitchExampleTests', :exclusive => true do
  pod "MCKillSwitch", :path => "../"
end