platform :ios, 5.0

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:mirego/MCPodSpecs.git'

link_with 'MCKillSwitchExample', 'MCKillSwitchExampleTests'

pod 'MCKillSwitch', :path => '../'
